name: Build macOS

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure
        run: |
          set -euxo pipefail
          # Ensure SDK is set so framework lookup works
          export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
          ./configure \
            --prefix="$PWD/build" \
            --disable-debug \
            --disable-doc \
            --disable-ffplay \
            --disable-x86asm \
            --enable-opencl \
            --extra-ldflags="-framework OpenCL"

      - name: Build
        run: |
          set -euxo pipefail
          make -j"$(sysctl -n hw.ncpu)"

      - name: Install
        run: |
          set -euxo pipefail
          make install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-${{ github.sha }}
          path: |
            build/bin/*
          if-no-files-found: error
